COLUMN_NAMES = {
    "DATE": "Date",
    "TYPE": "Type",
    "MARKET": "Marché",
    "NUMBER_OF_OFFERS": "Nombre d'annonces",
    "NOTES": "Notes",
    "TITLE": "Titre",
    "JOB_TITLE": "Intitulé",
    "TJM": "TJM",
    "SENIORITY": "Séniorité",
    "TECH_MAIN": "Technos principales",
    "TECH_SECONDARY": "Technos secondaires",
    "SKILL_MAIN": "Compétences principales",
    "SKILL_SECONDARY": "Compétences secondaires",
    "SECTOR": "Secteur",
    "LOCATION": "Localisation",
    "RHYTHM": "Rythme",
    "COMPANY": "Entreprise",
    "CONTACT": "Contact",
    "LINK": "Lien",
    "SOPHISTICATION": "Sophistication du marché",
    "LEARNING": "Capitalisation de l'apprentissage",
    "RELIABILITY": "Fiabilité"
}

COL_DATE = COLUMN_NAMES["DATE"]
COL_TYPE = COLUMN_NAMES["TYPE"]
COL_MARKET = COLUMN_NAMES["MARKET"]
COL_TITLE = COLUMN_NAMES["TITLE"]
COL_JOB_TITLE = COLUMN_NAMES["JOB_TITLE"]
COL_TJM = COLUMN_NAMES["TJM"]
COL_SENIORITY = COLUMN_NAMES["SENIORITY"]
COL_TECHS_MAIN = COLUMN_NAMES["TECH_MAIN"]
COL_TECHS_SECONDARY = COLUMN_NAMES["TECH_SECONDARY"]
COL_SKILLS_MAIN = COLUMN_NAMES["SKILL_MAIN"]
COL_SKILLS_SECONDARY = COLUMN_NAMES["SKILL_SECONDARY"]
COL_SECTOR = COLUMN_NAMES["SECTOR"]
COL_LOCATION = COLUMN_NAMES["LOCATION"]
COL_RHYTHM = COLUMN_NAMES["RHYTHM"]
COL_COMPANY = COLUMN_NAMES["COMPANY"]
COL_CONTACT = COLUMN_NAMES["CONTACT"]
COL_LINK = COLUMN_NAMES["LINK"]
COL_SOPHISTICATION = COLUMN_NAMES["SOPHISTICATION"]
COL_RELIABILITY = COLUMN_NAMES["RELIABILITY"]
COL_NUMBER_OF_OFFERS = COLUMN_NAMES["NUMBER_OF_OFFERS"]
COL_NOTES = COLUMN_NAMES["NOTES"]