from .columns import COLUMN_NAMES

MARKET_COLUMN_KEYS = ["DATE", "MARKET", "NUMBER_OF_OFFERS", "NOTES"]
MARKET_DISPLAY_COLUMNS = [COLUMN_NAMES[key] for key in MARKET_COLUMN_KEYS]

OFFER_COLUMN_KEYS = [
    "DATE", "MARKET", "JOB_TITLE", "TJM", "SENIORITY",
    "TECH_MAIN", "TECH_SECONDARY", "SKILL_MAIN", "SKILL_SECONDARY",
    "SECTOR", "LOCATION", "RHYTHM", "COMPANY", "CONTACT", "LINK"
]
OFFER_DISPLAY_COLUMNS = [COLUMN_NAMES[key] for key in OFFER_COLUMN_KEYS]

COMPASS_COLUMN_KEYS = [
    "MARKET", "SKILL_MAIN", "SKILL_SECONDARY", "TECH_MAIN", "TECH_SECONDARY",
    "TJM", "SENIORITY", "SECTOR", "RHYTHM", "LOCATION"
]
COMPASS_DISPLAY_COLUMNS = [COLUMN_NAMES[key] for key in COMPASS_COLUMN_KEYS] + ["latitude", "longitude"]