[theme]
base = "light"

primaryColor = "#2f80ed"              
backgroundColor = "#f3f4f6"            
secondaryBackgroundColor = "#ffffff"  
textColor = "#1E1E1E"                 
font = "sans serif"